### ISSUE TITLE
Dedicated PayPal Package

### ISSUE THREAD

**Issue by johannesschobel** [naifalshaye/nova-paypal#1]
Hey @naifalshaye ,

i stumbled upon this package by accident - this looks nice. I was curious if it would be possible to "extract" the paypal connector and interaction into a separate package (e.g., `naifalshaye/laravel-paypal`) and then make the `nova-paypal` package use the api provided by `laravel-paypal`.

This would
a) make the packages more re-usable, because you could use the `laravel-paypal` package in an API-like setup as well (e.g., without nova)
b) develop your own non-nova frontent
c) have a way more modular software development approach

what do you think about it?
All the best

**Comment by naifalshaye** [comment]
Hey @johannesschobel ,

Laravel PayPal separate package has been created, now Nova PayPal uses it as you suggested.

https://github.com/naifalshaye/laravel-paypal
https://github.com/naifalshaye/nova-paypal

README has been updated in both packages.

Thanks for the inspiration :)

Best regards,
Naif
